config/routes.rb
GetStocks::Application.routes.draw do
  resources :users do
    resources :user_stocks, path: :stocks
  end
  
  resource :stocks

  root :to => 'users#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  attr_accessible :symbol, :pretty_symbol, :symbol_lookup_url, :company, :exchange, :exchange_timezone, :exchange_utc_offset, :exchange_closing, :divisor, :currency, :last, :high, :low, :volume, :avg_volume, :market_cap,:open, :y_close, :change,:perc_change,:delay, :trade_timestamp, :trade_date_utc,:trade_time_utc, :current_date_utc, :current_time_utc, :symbol_url, :chart_url, :disclaimer_url, :ecn_url, :isld_last, :isld_trade_date_utc, :isld_trade_time_ut, :brut_last, :brut_trade_date_utc, :brut_trade_time_utc, :daylight_savings

  has_many :user_stocks
  
  before_save :refresh
  
  def refresh
    data = StockQuote::Stock.quote(symbol)
    data.instance_values.map do |k,v| 
      self[k] = v
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  
end

app/models/user_stock.rb
class UserStock < ActiveRecord::Base
  attr_accessible :stock_id, :user_id, :symbol
  
  belongs_to :user
  belongs_to :stock
  
  validates :symbol,:user_id, :stock_id, presence: true
  validates_uniqueness_of :symbol, :scope=> [:user_id, :stock_id]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  # GET /user_stocks
  # GET /user_stocks.json
  def index
    @user = User.find(params[:user_id])
    @stocks = @user.stocks
    @stocks.each do |stock|
      stock.save if stock.updated_at >=  1.hour.ago
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_stocks }
    end
  end

  # GET /user_stocks/1
  # GET /user_stocks/1.json
  def show
    @user_stock = UserStock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_stock }
    end
  end

  # GET /user_stocks/new
  # GET /user_stocks/new.json
  def new
    @user = User.find(params[:user_id])
    @user_stock = UserStock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_stock }
    end
  end

  # GET /user_stocks/1/edit
  def edit
    @user_stock = UserStock.find(params[:id])
  end

  # POST /user_stocks
  # POST /user_stocks.json
  def create
    @user = User.find(params[:user_id])
    @stock = Stock.where(symbol: params[:user_stock][:symbol]).first_or_create
    params[:user_stock].merge!(stock_id: @stock.id)
    @user_stock = UserStock.new(params[:user_stock])

    respond_to do |format|
      if @user_stock.save
        format.html { redirect_to user_user_stocks_path(@user), notice: 'User stock was successfully created.' }
        format.json { render json: @user_stock, status: :created, location: @user_stock }
      else
        format.html { render action: "new" }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_stocks/1
  # PUT /user_stocks/1.json
  def update
    @user_stock = UserStock.find(params[:id])

    respond_to do |format|
      if @user_stock.update_attributes(params[:user_stock])
        format.html { redirect_to @user_stock, notice: 'User stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stocks/1
  # DELETE /user_stocks/1.json
  def destroy
    @user_stock = UserStock.find_by_symbol(params[:id])
    @user_stock.destroy

    respond_to do |format|
      format.html { redirect_to user_stocks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_user_stocks_path(@user.to_param), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetStocks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_stocks/_form.html.erb
<%= form_for([@user, @user_stock]) do |f| %>
  <% if @user_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @user_stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_stocks/edit.html.erb
<h1>Editing user_stock</h1>

<%= render 'form' %>

<%= link_to 'Show', user_user_stock_path(@user,@user_stock) %> |
<%= link_to 'Back', user_user_stocks_path(@user) %>

app/views/user_stocks/index.html.erb
<h1>Listing Stocks for <%= @user.name %></h1>

<table>
  <tr>
    <th>symbol</th>
    <th>pretty_symbol</th>
    <th>symbol_lookup_url</th>
    <th>company</th>
    <th>exchange</th>
    <th>exchange_timezone</th>
    <th>exchange_utc_offset</th>
    <th>exchange_closing</th>
    <th>divisor</th>
    <th>currency</th>
    <th>last</th>
    <th>high</th>
    <th>low</th>
    <th>volume</th>
    <th>avg_volume</th>
    <th>market_cap</th>
    <th>open</th>
    <th>y_close</th>
    <th>change</th>
    <th>perc_change</th>
    <th>delay</th>
    <th>trade_timestamp</th>
    <th>trade_date_utc</th>
    <th>trade_time_utc</th>
    <th>current_date_utc</th>
    <th>current_time_utc</th>
    <th>symbol_url</th>
    <th>chart_url</th>
    <th>disclaimer_url</th>
    <th>ecn_url</th>
    <th>isld_last</th>
    <th>isld_trade_date_utc</th>
    <th>isld_trade_time_utc</th>
    <th>brut_last</th>
    <th>brut_trade_date_utc</th>
    <th>brut_trade_time_utc</th>
    <th>daylight_savings</th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><%= stock.symbol %></td>
    <td><%= stock.symbol %></td>
    <td><%= stock.pretty_symbol %></td>
    <td><%= stock.symbol_lookup_url %></td>
    <td><%= stock.company %></td>
    <td><%= stock.exchange %></td>
    <td><%= stock.exchange_timezone %></td>
    <td><%= stock.exchange_utc_offset %></td>
    <td><%= stock.exchange_closing %></td>
    <td><%= stock.divisor %></td>
    <td><%= stock.currency %></td>
    <td><%= stock.last %></td>
    <td><%= stock.high %></td>
    <td><%= stock.low %></td>
    <td><%= stock.volume %></td>
    <td><%= stock.avg_volume %></td>
    <td><%= stock.market_cap %></td>
    <td><%= stock.open %></td>
    <td><%= stock.y_close %></td>
    <td><%= stock.change %></td>
    <td><%= stock.perc_change %></td>
    <td><%= stock.delay %></td>
    <td><%= stock.trade_timestamp %></td>
    <td><%= stock.trade_date_utc %></td>
    <td><%= stock.trade_time_utc %></td>
    <td><%= stock.current_date_utc %></td>
    <td><%= stock.current_time_utc %></td>
    <td><%= stock.symbol_url %></td>
    <td><%= stock.chart_url %></td>
    <td><%= stock.disclaimer_url %></td>
    <td><%= stock.ecn_url %></td>
    <td><%= stock.isld_last %></td>
    <td><%= stock.isld_trade_date_utc %></td>
    <td><%= stock.isld_trade_time_utc %></td>
    <td><%= stock.brut_last %></td>
    <td><%= stock.brut_trade_date_utc %></td>
    <td><%= stock.brut_trade_time_utc %></td>
    <td><%= stock.daylight_savings %></td>
    <td><%= link_to 'Destroy', user_user_stock_path(@user.to_param, stock.symbol), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User stock', new_user_user_stock_path(@user.to_param) %>

app/views/user_stocks/new.html.erb
<h1>New user_stock</h1>

<%= render 'form' %>

<%= link_to 'Back', user_user_stocks_path(@user) %>

app/views/user_stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_stock.user_id %>
</p>

<p>
  <b>Stock:</b>
  <%= @user_stock.stock_id %>
</p>


<%= link_to 'Edit', edit_user_user_stock_path(@user, @user_stock) %> |
<%= link_to 'Back', user_user_stocks_path(@user) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>